# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bahadira/Desktop/Workspace/PythonTutorials/QtDesigner/ComboBox/ComboBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CBSehirler = QtWidgets.QComboBox(self.centralwidget)
        self.CBSehirler.setGeometry(QtCore.QRect(160, 120, 271, 51))
        self.CBSehirler.setObjectName("CBSehirler")
        self.LBResult = QtWidgets.QLabel(self.centralwidget)
        self.LBResult.setGeometry(QtCore.QRect(160, 40, 271, 61))
        self.LBResult.setAlignment(QtCore.Qt.AlignCenter)
        self.LBResult.setObjectName("LBResult")
        self.BTGetItem = QtWidgets.QPushButton(self.centralwidget)
        self.BTGetItem.setGeometry(QtCore.QRect(160, 250, 121, 61))
        self.BTGetItem.setObjectName("BTGetItem")
        self.BTLoadItem = QtWidgets.QPushButton(self.centralwidget)
        self.BTLoadItem.setGeometry(QtCore.QRect(308, 250, 121, 61))
        self.BTLoadItem.setObjectName("BTLoadItem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LBResult.setText(_translate("MainWindow", "TextLabel"))
        self.BTGetItem.setText(_translate("MainWindow", "GetItem"))
        self.BTLoadItem.setText(_translate("MainWindow", "Load Items"))
