# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bahadira/Desktop/Projects/VisualCodeWorkspace/Python/PythonTutorials/QtDesigner/FirstDesign/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 387)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(70, 40, 51, 31))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(70, 110, 51, 31))
        self.label2.setObjectName("label2")
        self.txtsayi1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtsayi1.setGeometry(QtCore.QRect(140, 50, 113, 25))
        self.txtsayi1.setObjectName("txtsayi1")
        self.txtsayi2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtsayi2.setGeometry(QtCore.QRect(140, 110, 113, 25))
        self.txtsayi2.setObjectName("txtsayi2")
        self.btntopla = QtWidgets.QPushButton(self.centralwidget)
        self.btntopla.setGeometry(QtCore.QRect(20, 160, 89, 41))
        self.btntopla.setObjectName("btntopla")
        self.btncikar = QtWidgets.QPushButton(self.centralwidget)
        self.btncikar.setGeometry(QtCore.QRect(130, 160, 89, 41))
        self.btncikar.setObjectName("btncikar")
        self.btnbol = QtWidgets.QPushButton(self.centralwidget)
        self.btnbol.setGeometry(QtCore.QRect(230, 160, 89, 41))
        self.btnbol.setObjectName("btnbol")
        self.btncarp = QtWidgets.QPushButton(self.centralwidget)
        self.btncarp.setGeometry(QtCore.QRect(330, 160, 89, 41))
        self.btncarp.setObjectName("btncarp")
        self.sonuc = QtWidgets.QLabel(self.centralwidget)
        self.sonuc.setGeometry(QtCore.QRect(110, 230, 151, 61))
        self.sonuc.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.sonuc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sonuc.setAlignment(QtCore.Qt.AlignCenter)
        self.sonuc.setObjectName("sonuc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 471, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "Sayı 1:"))
        self.label2.setText(_translate("MainWindow", "Sayı 2:"))
        self.btntopla.setText(_translate("MainWindow", "Toplama"))
        self.btncikar.setText(_translate("MainWindow", "Çıkarma"))
        self.btnbol.setText(_translate("MainWindow", "Bölme"))
        self.btncarp.setText(_translate("MainWindow", "Çarpma"))
        self.sonuc.setText(_translate("MainWindow", "Sonuc"))

    