# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bahadira/Desktop/Workspace/PythonTutorials/QtDesigner/CheckBox/CheckBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ButonSecim = QtWidgets.QPushButton(self.centralwidget)
        self.ButonSecim.setGeometry(QtCore.QRect(110, 320, 241, 71))
        self.ButonSecim.setObjectName("ButonSecim")
        self.LabelResult = QtWidgets.QLabel(self.centralwidget)
        self.LabelResult.setGeometry(QtCore.QRect(400, 70, 181, 231))
        self.LabelResult.setObjectName("LabelResult")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(110, 70, 241, 231))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CbSinema = QtWidgets.QCheckBox(self.widget)
        self.CbSinema.setObjectName("CbSinema")
        self.verticalLayout.addWidget(self.CbSinema)
        self.CbKitap = QtWidgets.QCheckBox(self.widget)
        self.CbKitap.setObjectName("CbKitap")
        self.verticalLayout.addWidget(self.CbKitap)
        self.CbSpor = QtWidgets.QCheckBox(self.widget)
        self.CbSpor.setObjectName("CbSpor")
        self.verticalLayout.addWidget(self.CbSpor)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ButonSecim.setText(_translate("MainWindow", "Seçimleri Al"))
        self.LabelResult.setText(_translate("MainWindow", "Seçimler"))
        self.CbSinema.setText(_translate("MainWindow", "Sinema"))
        self.CbKitap.setText(_translate("MainWindow", "Kitap Okumak"))
        self.CbSpor.setText(_translate("MainWindow", "Spor"))
